[package]
name = "gold"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = "0.65.1"
cc = "1.0.79"
gobuild = "0.1.0-alpha.2"

[dependencies]
tree-sitter = { git = "https://github.com/tree-sitter/tree-sitter.git" }
walkdir = "2.3.3"

[dev-dependencies]
pretty_assertions = "1.2.1"